### ISSUE TITLE
 module 'popfix.action' not found:`

### ISSUE THREAD

**Issue by teto** [RishabhRD/nvim-lsputils#10]
I've added this to my init.vim
```
Plug 'RishabhRD/popfix' " to manage underlying popup and previews
Plug 'RishabhRD/nvim-lsputils' " for lsp codeactions
```
Installed/updated 
but on startup I get
`E5113: Error while calling lua chunk: .../share/nvim/site/nvim-lsputils/lua/lsputil/locations.lua:4: module 'popfix.action' not found:`

**Comment by RishabhRD** [comment]
Hi, This should not happen. I reinstalled the plugin myself and I checked on some more systems. However, I was not able to reproduce the behaviour.  Which plugin manager are you using? I tried with vim-plug. I didn't check with other plugin managers(however some people who created issue in past used different plugin managers). So, maybe I need to check with your plugin manager.
