### ISSUE TITLE
Behavior changed in new version?

### ISSUE THREAD

**Issue by ray-x** [RishabhRD/nvim-lsputils#11]
Hi, RishabhRD

It seems that the plugin behavior changed in recent version.
If I do "reference". The plugin shows the reference and preview.
But if I open the file by hitting <CR>
The plugin will prompt 
```
1 buffer wiped out
2 buffer wiped out
Press ENTER or type command to continue
```
Options 1 and 2 are same. 
Is there configuration I need to add so it could bring me directly to the file/line I selected?

Also I find that each time this plugin was triggered, it will create a no-name buffer, it is a bit annoying as I need to "bdelete" manually from time to time. Is there a way it could be delete automatically after  preview closed?  

Also, Is there a way I could open new buffer in a vsplit view?

**Comment by RishabhRD** [comment]
Seems like I merged the buggy code to master. I recently accepted my fellow mate code for some improvement. Seems like it has some bugs. I would fix that in some hours.:neutral_face:

**Comment by RishabhRD** [comment]
Currently vsplit thing is not there. But I am working on it. I would merge it in 2-3 days☺️

**Comment by RishabhRD** [comment]
I just pushed the code to wipe that no name buffer to popfix. But I was not able to regenerate that '1 buffer wiped out' behaviour. Can you link your neovim config. Maybe it would be helpful for regenerating that behaviour. Thanks for reporting this critical issue.

**Comment by ray-x** [comment]
Hi, RishabhRD 
Thanks for the fix for `No Name` buffer. Issue resolved with latest version

For the 
```
1 buffer wiped out
2 buffer wiped out
Press ENTER or type command to continue
```
I double check the config and did some diff with my historical setup.  It seems the setup
`set report=0` vs `set report=2` cause this issue.

If I setup report=0, I can see the extra prompet, if leave it as default(2), it is fine.

**Comment by RishabhRD** [comment]
It's normal behavior with set report = 0 as it would report because 3 buffers are closed simultaneously. Because you also know it so I think we can close the issue. Thanks for reporting🙂.

**Comment by ray-x** [comment]
Thanks! Issue closed.
