### ISSUE TITLE
Feature request UI option config

### ISSUE THREAD

**Issue by ray-x** [RishabhRD/nvim-lsputils#12]
I would like to config the UI through vimrc. Personally following config works for me:  It would be great to pass the opts (at least some of the fields e.g height, mode) to plugin.
Also did not find how to control the ratio of the symbols list and preview window, e.g I would like the window looks like this, in which more space left for preview window.

|   symbols 	|   &nbsp; &nbsp;  &nbsp; &nbsp;    &nbsp; &nbsp;      preview    &nbsp; &nbsp;      &nbsp; &nbsp;  &nbsp; &nbsp; 	| 
|---	|---	|

Current opts I am using:

```lua
  local opts = {
    mode = 'editor',
    data = data,
    height = 24,
    keymaps = keymaps,
    additional_keymaps = additionalKeymaps,
    callbacks = {
      select = selection_handler,
      close = close_handler
    },
    list = {
      numbering = true
    },
    preview = {
      type = 'terminal',
      border = false,
      title = 'Preview',
    }
  }
```

**Comment by RishabhRD** [comment]
Yeah your suggestions are great. Currently we can't pass opts argument directly to nvim-lsputils however, something like custom themes would be great in which we can change mode, height, etc.
For the ratio thing I would need to change the core 'popfix' . And would be good feature for popfix also. I would start with custom themes and then to ratio. Thanks for suggestions :smile:

**Comment by ray-x** [comment]
Ideally, the height would be a float to specify the ratio of  height compared to current window size.  So it could adapt to different screen size.
If we enable mode = editor, there will be more fields to config. I would not worried about that for now. The default works just fine for me. Split works in a no-disturb way, however, float is cool.

**Comment by RishabhRD** [comment]
I just tried your opts and it really looks so cool that I want to use these opts as default!!!!  Passing opts to function itself is not possible because configuration options given to users directly invoke neovim LSP callbacks and changing them would break backward compatibility. However, this can be provided as a global variable. Global variables options are also preferable because they can be configured using Lua as well as vimscript. (Vimscript natively without lua keyword).

**Comment by RishabhRD** [comment]
I updated the code. Now users can add customization using global variables provided. I think this should be sufficient for passing custom opts. This update doesn't include the ratio thing for now.

**Comment by ray-x** [comment]
Hi, @RishabhRD 
Great, it works.
Just a minor issue in Readme.md:

```lua
		n = {
			['<C-n>'] = 'j'
			['<C-p>'] = 'k'
		}
```
Should be 
```lua
		n = {
			['<C-n>'] = 'j',
			['<C-p>'] = 'k',
		}
```

**Comment by RishabhRD** [comment]
Ok I would fix that. So, thanks :smile:
