### ISSUE TITLE
[feature request] customizable border characters

### ISSUE THREAD

**Issue by smartding** [RishabhRD/nvim-lsputils#15]
The default double line border is a bit too much to my taste, can we have customizable border characters? So that I can set a single line border.

**Comment by RishabhRD** [comment]
Yes! I myself wanted to add this feature because I also prefer single borders but many people just like double borders. I would implement it. It would take 2-3 days because I am a little busy these days. But surely I am gonna add it. :smiley:

**Comment by RishabhRD** [comment]
I just added custom border_chars options for the list and preview attributes. Also, I made single border characters default now because people who like double border characters can customize it.
