### ISSUE TITLE
screencast

### ISSUE THREAD

**Issue by RishabhRD** [RishabhRD/nvim-lsputils#2]
![fix_import](https://user-images.githubusercontent.com/26287448/93617774-076ad600-f9f4-11ea-9c4e-d37019241320.gif)
![references](https://user-images.githubusercontent.com/26287448/93617977-4e58cb80-f9f4-11ea-9406-6e0ff0f2ec93.gif)
)

**Comment by RishabhRD** [comment]
![references_colored](https://user-images.githubusercontent.com/26287448/93930985-d3691b00-fd3b-11ea-9053-b699e4d36558.gif)

**Comment by alexaandru** [comment]
Hello,

First of all thank you for this great plugin!

I cannot figure how to activate that code actions popup menu from the first screencast. I do have the references working (for example) and it is much nicer than the location list :-) Not sure what am I doing wrong/missing for the code actions popup though...

Thanks!

**Comment by RishabhRD** [comment]
Hi! Thanks for feedback. Normally for triggering code actions, you need to be on line have diagnostics and code action possible(supported by language server) and then press your code action trigger key map. However, I think this is not working for you. So, can you share a gif or screencast of how code action trigger reacts when you press it and your config so that we can find out what is getting wrong.

**Comment by alexaandru** [comment]
I do have on line diagnostics (I think - I do get errors when I type something wrong). I am only using (well, were so far) the builtin LSP functionality + nvim-lspconfig plugin. I do use some code actions on save (format for example) so those are working too, I think.

Here is my config: https://gist.github.com/alexaandru/9449a9d838c8632fad91ef35d4f6fd43 I just cloned the repos (as git submodules of a `pack` repo) and that's how I add/update them. Tried to keep it as simple/bare bone as possible in favor of using as much as I can from builtin features :-)

As for the screencast, not sure what I should record, not sure how to "trigger code actions". I can show you my LSP configuration (for Go, for example, or for any other if it helps):

```JSON
{
  codeActionProvider = true,
  codeLensProvider = vim.empty_dict(),
  completionProvider = {
    triggerCharacters = { "." }
  },
  definitionProvider = true,
  documentFormattingProvider = true,
  documentHighlightProvider = true,
  documentLinkProvider = vim.empty_dict(),
  documentOnTypeFormattingProvider = {
    firstTriggerCharacter = ""
  },
  documentSymbolProvider = true,
  executeCommandProvider = {
    commands = { "generate", "fill_struct", "regenerate_cgo", "test", "tidy", "undeclared_name", "upgrade_dependency", "vendor", "extract_variable", "extract_function" }
  },
  foldingRangeProvider = true,
  hoverProvider = true,
  implementationProvider = true,
  referencesProvider = true,
  renameProvider = true,
  signatureHelpProvider = {
    triggerCharacters = { "(", "," }
  },
  textDocumentSync = {
    change = 2,
    openClose = true,
    save = vim.empty_dict()
  },
  typeDefinitionProvider = true,
  workspace = {
    workspaceFolders = {
      changeNotifications = "workspace/didChangeWorkspaceFolders",
      supported = true
    }
  },
  workspaceSymbolProvider = true
}
```

Thanks so much for looking into it! :)

**Comment by RishabhRD** [comment]
It would take me some time to go through the configurations. I would through it and inform you. :-)

**Comment by RishabhRD** [comment]
Hello, I just went through your configurations, I didn't find any code_action mapping in it. Actually you can trigger code_action using 
`vim.lsp.buf.code_action()`
So, you can map it something like: `nnoremap <silent> <leader>af <cmd>lua vim.lsp.buf.code_action()<cr>`
I think similar mapping would solve your issue. :-)

**Comment by alexaandru** [comment]
That was it! Thank you so much!! :) I now have them :)

I was following the docs at https://neovim.io/doc/user/lsp.html that's how I added all the other mappings for LSP, but there was no mention of a mapping for code actions.

**Comment by ludwj61** [comment]
Hi I have a question unrelated to your plugin, if you don't mind. I notice in your examples you use the JDTLS with nvim lsp. Do you ever notice that you are "missing" code actions? 

To elaborate, with coc.nvim, I always get options like generate getters and setters, toString(), etc. but with built in LSP, those options are frequently missing.

Thanks again for the plugin

**Comment by RishabhRD** [comment]
@ludwj61 hi! Normally the plugin takes information from LSP server and display it in customised fashion. But as you told some results are missing in compare to coc. That creates a possibility that they(coc-java) cache some results and display it every time, as server doesn't send that result. I need to check coc-java for this. This may take some time. But we can figure out if it is this nvim-lsp mistake or nvim-lspconfig mistake for jdtls. It's rare that it's nvim-lsputils mistake because we are sort of redirecting the suggestions. Thanks for reporting. I would inform you after looking into the coc-java code. :smile:

**Comment by ludwj61** [comment]
@RishabhRD just want to say I found the reason for this. Apparently the JDTLS does unconventional things which makes nvim-lspconfig's implementation incomplete.

If you are interested as well, there is a much more complete implementation with https://github.com/mfussenegger/nvim-jdtls that still uses built-in LSP.

**Comment by RishabhRD** [comment]
I just looked into the repository. It's really cool. jdtls does some 'incorrect' implementation of protocol that's why hard to manage it without any 'extension'.(They are trying to ship correct implementation in next version as one contributor told me on gitter). And this repository does that really well. Thanks for mentioning it.

**Comment by RishabhRD** [comment]
editor mode screenshot
![theme](https://user-images.githubusercontent.com/26287448/98858320-6abe3500-2486-11eb-8795-a8d1bb8dbecc.gif)

**Comment by RishabhRD** [comment]
updated references screenshot: 

![references](https://user-images.githubusercontent.com/26287448/98860407-9ee72500-2489-11eb-8b61-4ca7cb3f78ee.gif)

**Comment by RishabhRD** [comment]
Updated codeaction screenshot
![codeaction](https://user-images.githubusercontent.com/26287448/98861852-f7b7bd00-248b-11eb-8c11-fd37ab5d45d7.gif)

**Comment by RishabhRD** [comment]
fuzzy search screenshot
![fzf](https://user-images.githubusercontent.com/26287448/100377758-de8c4000-3037-11eb-9969-c4edfc9b5479.gif)

**Comment by RishabhRD** [comment]
fzf updated screencast
![fzf](https://user-images.githubusercontent.com/26287448/100378731-abe34700-3039-11eb-98e6-151007b49d5a.gif)
