### ISSUE TITLE
Error executing vim.schedule lua callback: .../.config/nvim/plugged/nvim-lsputils/lua/lsputil/util.lua:89: attempt to index local 'var' (a userdata value)

### ISSUE THREAD

**Issue by hungrybirder** [RishabhRD/nvim-lsputils#26]
Hello
Thank you for this useful plugin.
But I got a problem and I don't know why?

my lsputils.lua
```
vim.lsp.handlers['textDocument/codeAction'] = require'lsputil.codeAction'.code_action_handler
vim.lsp.handlers['textDocument/references'] = require'lsputil.locations'.references_handler
vim.lsp.handlers['textDocument/definition'] = require'lsputil.locations'.definition_handler
vim.lsp.handlers['textDocument/declaration'] = require'lsputil.locations'.declaration_handler
vim.lsp.handlers['textDocument/typeDefinition'] = require'lsputil.locations'.typeDefinition_handler
vim.lsp.handlers['textDocument/implementation'] = require'lsputil.locations'.implementation_handler
vim.lsp.handlers['textDocument/documentSymbol'] = require'lsputil.symbols'.document_handler
vim.lsp.handlers['workspace/symbol'] = require'lsputil.symbols'.workspace_handler
```

When I type `gr` in normal, I got a error.
![image](https://user-images.githubusercontent.com/1021047/119095326-ba3c7980-ba44-11eb-9682-54f0791023d4.png)

I don't know why. It's that the latest neovim bug or something I got wrong?  Please let me know. Thank you.

Some Info:
nvim-lsputils commit id : b68862afee6dfb611d866818cafdba41cf51d749
NVIM v0.5.0-dev+1342-gde96626ad
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by hungrybirder** [comment]
I just upgrade neovim to
:version
NVIM v0.5.0-dev+1343-g75992f2ad
Build type: Release
LuaJIT 2.1.0-beta3

The error is still there. :)

**Comment by hungrybirder** [comment]
I downgrade neovim to https://github.com/neovim/neovim/commit/6deae3d14b59f554a352b9e3738a7a4acb254ea3.
It works well.

![Uploading image.png…]()

**Comment by RishabhRD** [comment]
I am working on bug. I didn't update to new commits so I didn't face it and didn't update the codebase.  I would post an update in few hour. Thanks for reporting.

**Comment by miguelcaravantes** [comment]
same error in last neovim version

**Comment by Chaitanyabsprip** [comment]
I am still facing this, forced to disable it until it gets fixed
