### ISSUE TITLE
Preview window is broken

### ISSUE THREAD

**Issue by roflolilolmao** [RishabhRD/nvim-lsputils#32]
On my system (nvim 0.5, Windows 10), the preview window (for example when searching for references), contains a `bat` error:

```
error: Found argument '-R' which wasn't expected, or isn't valid in this context

USAGE:
    bat.exe --color <when> --number --pager <command> --paging <when> --plain

For more information try --help

[Process exited 1]
```

I believe using double quotes instead of single quotes in the `pager` parameter of the following line would fix this issue:

https://github.com/RishabhRD/nvim-lsputils/blob/f34927f8ec777f4e91e14afc709de9da1cd70116/lua/lsputil/actions.lua#L48

Thank you. :-)

**Comment by RishabhRD** [comment]
Thanks for reporting. I would merge the changes after few tests. It should take mostly some hours.
