### ISSUE TITLE
`codeAction` tries to spawn a popfix `floating_win` with negative height

### ISSUE THREAD

**Issue by hood** [RishabhRD/nvim-lsputils#37]
I have the following override in place
```
vim.lsp.handlers['textDocument/codeAction'] = require'lsputil.codeAction'.code_action_handler
```

And, since yesterday, whenever I try to do
```
lua vim.lsp.buf.code_action()
```

I get the following error:
```
Error executing vim.schedule lua callback: .../.config/nvim/plugged/popfix/lua/popfix/floatin_win.lua:37: 'height' key must be a positive Integer
```

**Comment by xanderio** [comment]
Properly related to #30

**Comment by RishabhRD** [comment]
https://github.com/neovim/neovim/pull/15504 was merged yesterday that changed lsp-handler-spec. Updated the handler-specs in nvim-lsputils to match the same.

**Comment by xanderio** [comment]
Did you possible forget to push this?

**Comment by RishabhRD** [comment]
@xanderio lol yeah I fogot to push :joy: I pushed it now

**Comment by hood** [comment]
Thanks.
