### ISSUE TITLE
attempt to index local 'border_ chars' (a boolean value)

### ISSUE THREAD

**Issue by cathaysia** [RishabhRD/nvim-lsputils#48]
just like this:

![图片](https://user-images.githubusercontent.com/42114817/140631355-85d8dbed-b69a-4f9c-afc1-d2844e59c58c.png)

**Comment by RishabhRD** [comment]
I merged a PR without testing... I would revert that back. My fault

**Comment by RishabhRD** [comment]
Please update the popfix plugin. It should be fixed now.

**Comment by cathaysia** [comment]
Yes, this be fixed. :)
![图片](https://user-images.githubusercontent.com/42114817/140634981-27db959e-2784-4a2b-aced-391a14fc3585.png)

**Comment by vstegen** [comment]
Ran into the same issue with neovim 0.6 and have the current versions of popfix and lsputils installed.

I had this problem when looking for references and looking through the code, it seems like at lsputils sets the border option to `true`: https://github.com/RishabhRD/nvim-lsputils/blob/master/lua/lsputil/locations.lua#L51 which then gets passed down until it reaches the `fill_border_data` function in https://github.com/RishabhRD/popfix/blob/f3571e676739208871bd38f9fa0fddf554b6a7a8/lua/popfix/floating_win.lua#L64

As `border_chars` is true, it tries to use index the boolean variable afterwards, causing this issue. If exchanged line 65 in the same file with

```
border_chars = type(border_chars) == "table" and border_chars or default_border_chars
```

which works for me for now. Not sure if that would be a viable solution to this problem in the long ran as I'm not sure if some other code path breaks with the change.
