### ISSUE TITLE
Simpler close of reference handler window

### ISSUE THREAD

**Issue by kaddkaka** [RishabhRD/nvim-lsputils#7]
Would it be possible to change the reference window to close immediately on `q`? (like `:Gblame` window)

**Comment by RishabhRD** [comment]
Yes it would be. For the time being it closes if you press \<Esc\> but even I felt this would be convenient. Maybe I would add it in some hours today itself.

**Comment by RishabhRD** [comment]
enhancement pushed in master! Closing now :-)

**Comment by RishabhRD** [comment]
I just realised you are asking in promgrammatic way I guess. If so, yes we are working.

**Comment by RishabhRD** [comment]
a0450e3312fc943afb0394481400ac7010e9f3e2 provides custom keymap features. It is now merged in master. You can reference readme to get more about it. Thanks for reporting :-)
